---
- name: Create an EC2 instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Launch instance
      ec2:
         key_name: testkey3
         group: ansible-node
         instance_type: t2.micro
         image: ami-0be2609ba883822ec
         aws_access_key: "<ACCESS KEY ID>"
         aws_secret_key: "<SECRET ACCESS KEY>"
         wait: true
         region: us-east-1

      register: ec2
    - name: Print all ec2 variables
      debug: var=ec2
    - name: Get the Ip address
      debug: var=ec2.instances[0].public_dns_name

    - pause: minutes=1

